## Importing libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [2]:
iondata = pd.read_csv("ionosphere.data",header=None)

In [3]:
iondata.head()

0   1        2        3        4        5        6        7        8   \
0   1   0  0.99539 -0.05889  0.85243  0.02306  0.83398 -0.37708  1.00000   
1   1   0  1.00000 -0.18829  0.93035 -0.36156 -0.10868 -0.93597  1.00000   
2   1   0  1.00000 -0.03365  1.00000  0.00485  1.00000 -0.12062  0.88965   
3   1   0  1.00000 -0.45161  1.00000  1.00000  0.71216 -1.00000  0.00000   
4   1   0  1.00000 -0.02401  0.94140  0.06531  0.92106 -0.23255  0.77152   

        9   ...       25       26       27       28       29       30  \
0  0.03760  ... -0.51171  0.41078 -0.46168  0.21266 -0.34090  0.42267   
1 -0.04549  ... -0.26569 -0.20468 -0.18401 -0.19040 -0.11593 -0.16626   
2  0.01198  ... -0.40220  0.58984 -0.22145  0.43100 -0.17365  0.60436   
3  0.00000  ...  0.90695  0.51613  1.00000  1.00000 -0.20099  0.25682   
4 -0.16399  ... -0.65158  0.13290 -0.53206  0.02431 -0.62197 -0.05707   

        31       32       33  34  
0 -0.54487  0.18641 -0.45300   g  
1 -0.06288 -0.13738 -0.02447   b  
2 -0.24180  0.56045 -0.38238   g  
3  1.00000 -0.32382  1.00000   b  
4 -0.59573 -0.04608 -0.65697   g  

[5 rows x 35 columns]

In [4]:
iondata.shape


(351, 35)

In [5]:
X = iondata.drop(34, axis=1)
y = iondata[34]

In [6]:
y

0      g
1      b
2      g
3      b
4      g
      ..
346    g
347    g
348    g
349    g
350    g
Name: 34, Length: 351, dtype: object

In [7]:
X

0   1        2        3        4        5        6        7        8   \
0     1   0  0.99539 -0.05889  0.85243  0.02306  0.83398 -0.37708  1.00000   
1     1   0  1.00000 -0.18829  0.93035 -0.36156 -0.10868 -0.93597  1.00000   
2     1   0  1.00000 -0.03365  1.00000  0.00485  1.00000 -0.12062  0.88965   
3     1   0  1.00000 -0.45161  1.00000  1.00000  0.71216 -1.00000  0.00000   
4     1   0  1.00000 -0.02401  0.94140  0.06531  0.92106 -0.23255  0.77152   
..   ..  ..      ...      ...      ...      ...      ...      ...      ...   
346   1   0  0.83508  0.08298  0.73739 -0.14706  0.84349 -0.05567  0.90441   
347   1   0  0.95113  0.00419  0.95183 -0.02723  0.93438 -0.01920  0.94590   
348   1   0  0.94701 -0.00034  0.93207 -0.03227  0.95177 -0.03431  0.95584   
349   1   0  0.90608 -0.01657  0.98122 -0.01989  0.95691 -0.03646  0.85746   
350   1   0  0.84710  0.13533  0.73638 -0.06151  0.87873  0.08260  0.88928   

          9   ...       24       25       26       27       28       29  \
0    0.03760  ...  0.56811 -0.51171  0.41078 -0.46168  0.21266 -0.34090   
1   -0.04549  ... -0.20332 -0.26569 -0.20468 -0.18401 -0.19040 -0.11593   
2    0.01198  ...  0.57528 -0.40220  0.58984 -0.22145  0.43100 -0.17365   
3    0.00000  ...  1.00000  0.90695  0.51613  1.00000  1.00000 -0.20099   
4   -0.16399  ...  0.03286 -0.65158  0.13290 -0.53206  0.02431 -0.62197   
..       ...  ...      ...      ...      ...      ...      ...      ...   
346 -0.04622  ...  0.95378 -0.04202  0.83479  0.00123  1.00000  0.12815   
347  0.01606  ...  0.94520  0.01361  0.93522  0.04925  0.93159  0.08168   
348  0.02446  ...  0.93988  0.03193  0.92489  0.02542  0.92120  0.02242   
349  0.00110  ...  0.91050 -0.02099  0.89147 -0.07760  0.82983 -0.17238   
350 -0.09139  ...  0.86467 -0.15114  0.81147 -0.04822  0.78207 -0.00703   

          30       31       32       33  
0    0.42267 -0.54487  0.18641 -0.45300  
1   -0.16626 -0.06288 -0.13738 -0.02447  
2    0.60436 -0.24180  0.56045 -0.38238  
3    0.25682  1.00000 -0.32382  1.00000  
4   -0.05707 -0.59573 -0.04608 -0.65697  
..       ...      ...      ...      ...  
346  0.86660 -0.10714  0.90546 -0.04307  
347  0.94066 -0.00035  0.91483  0.04712  
348  0.92459  0.00442  0.92697 -0.00577  
349  0.96022 -0.03757  0.87403 -0.16243  
350  0.75747 -0.06678  0.85764 -0.06151  

[351 rows x 34 columns]

## Train-Test Split

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)

## Linear Kernel

In [9]:
svclassifier1 = SVC(kernel='linear')
svclassifier1.fit(X_train, y_train)

SVC(kernel='linear')

In [10]:
y_pred1 = svclassifier1.predict(X_test)

In [11]:
print(confusion_matrix(y_test,y_pred1))
print(classification_report(y_test,y_pred1))

[[16 13]
 [ 2 40]]
              precision    recall  f1-score   support

           b       0.89      0.55      0.68        29
           g       0.75      0.95      0.84        42

    accuracy                           0.79        71
   macro avg       0.82      0.75      0.76        71
weighted avg       0.81      0.79      0.78        71



## Quadratic Kernel

In [12]:
svclassifier2 = SVC(kernel='poly', degree=2)
svclassifier2.fit(X_train, y_train)

SVC(degree=2, kernel='poly')

In [13]:
y_pred2 = svclassifier2.predict(X_test)

In [14]:
print(confusion_matrix(y_test, y_pred2))
print(classification_report(y_test, y_pred2))

[[24  5]
 [ 3 39]]
              precision    recall  f1-score   support

           b       0.89      0.83      0.86        29
           g       0.89      0.93      0.91        42

    accuracy                           0.89        71
   macro avg       0.89      0.88      0.88        71
weighted avg       0.89      0.89      0.89        71



## Radial Basis Function Kernel

In [15]:
svclassifier3 = SVC(kernel='rbf')
svclassifier3.fit(X_train, y_train)

SVC()

In [16]:
y_pred3 = svclassifier3.predict(X_test)

In [17]:
print(confusion_matrix(y_test, y_pred3))
print(classification_report(y_test, y_pred3))

[[25  4]
 [ 2 40]]
              precision    recall  f1-score   support

           b       0.93      0.86      0.89        29
           g       0.91      0.95      0.93        42

    accuracy                           0.92        71
   macro avg       0.92      0.91      0.91        71
weighted avg       0.92      0.92      0.91        71



## Finding Generalization Constant Empirically

In [18]:
parameters = [{'kernel': ['linear'], 'C': [1, 10, 100, 1000]},
              {'kernel': ['poly'], 'C': [1, 10, 100, 1000],'degree':[2]},
              {'kernel': ['rbf'], 'C': [1, 10, 100, 1000]}]

In [19]:
parameters

[{'kernel': ['linear'], 'C': [1, 10, 100, 1000]},
 {'kernel': ['poly'], 'C': [1, 10, 100, 1000], 'degree': [2]},
 {'kernel': ['rbf'], 'C': [1, 10, 100, 1000]}]

In [20]:
svc = SVC()

In [21]:
clf = GridSearchCV(svc,parameters)

In [22]:
clf.fit(X_train,y_train)

GridSearchCV(estimator=SVC(),
             param_grid=[{'C': [1, 10, 100, 1000], 'kernel': ['linear']},
                         {'C': [1, 10, 100, 1000], 'degree': [2],
                          'kernel': ['poly']},
                         {'C': [1, 10, 100, 1000], 'kernel': ['rbf']}])

In [23]:
sorted(clf.cv_results_.keys())

['mean_fit_time',
 'mean_score_time',
 'mean_test_score',
 'param_C',
 'param_degree',
 'param_kernel',
 'params',
 'rank_test_score',
 'split0_test_score',
 'split1_test_score',
 'split2_test_score',
 'split3_test_score',
 'split4_test_score',
 'std_fit_time',
 'std_score_time',
 'std_test_score']

In [24]:
clf.cv_results_

{'mean_fit_time': array([0.00359197, 0.00597291, 0.04403052, 0.07197428, 0.0030076 ,
        0.00300126, 0.00301304, 0.00359035, 0.00361395, 0.0032002 ,
        0.00361204, 0.00338321]),
 'std_fit_time': array([4.90530832e-04, 8.96885689e-04, 5.74435075e-02, 2.29048950e-02,
        1.99220944e-05, 2.02498094e-05, 1.99319073e-05, 4.76329080e-04,
        4.71109924e-04, 3.96617905e-04, 4.75759719e-04, 4.80773708e-04]),
 'mean_score_time': array([0.00161233, 0.0016057 , 0.00159416, 0.00159531, 0.00159726,
        0.0019938 , 0.00198965, 0.00139585, 0.00178699, 0.00180235,
        0.0013895 , 0.00161486]),
 'std_score_time': array([4.84048027e-04, 4.79537693e-04, 4.87450959e-04, 4.85455014e-04,
        4.89185904e-04, 2.04873572e-06, 1.29971150e-05, 4.89084963e-04,
        3.94807962e-04, 3.90656262e-04, 4.81488856e-04, 4.96618893e-04]),
 'param_C': masked_array(data=[1, 10, 100, 1000, 1, 10, 100, 1000, 1, 10, 100, 1000],
              mask=[False, False, False, False, False, False, False,

In [25]:
clf.best_params_

{'C': 10, 'kernel': 'rbf'}

In [26]:
clf.best_estimator_

SVC(C=10)

In [27]:
clf.best_score_

0.9464285714285714

In [28]:
clf.best_index_

9

In [29]:
clf.refit_time_

0.0029909610748291016

## Taking C=10 and building Comparison Table

### Linear Kernel

In [30]:
svclassifier1 = SVC(C=10,kernel='linear')
svclassifier1.fit(X_train, y_train)

y_pred1 = svclassifier1.predict(X_test)

print(confusion_matrix(y_test,y_pred1))
print(classification_report(y_test,y_pred1))

[[17 12]
 [ 4 38]]
              precision    recall  f1-score   support

           b       0.81      0.59      0.68        29
           g       0.76      0.90      0.83        42

    accuracy                           0.77        71
   macro avg       0.78      0.75      0.75        71
weighted avg       0.78      0.77      0.77        71



In [31]:
test_acc_1 = accuracy_score(y_test,y_pred1)

y_pred1_train = svclassifier1.predict(X_train)

train_acc_1 = accuracy_score(y_train,y_pred1_train)

test_acc_1, train_acc_1

(0.7746478873239436, 0.9535714285714286)

### Quadratic Kernel

In [32]:
svclassifier2 = SVC(C=10,kernel='poly', degree=2)
svclassifier2.fit(X_train, y_train)

y_pred2 = svclassifier2.predict(X_test)

print(confusion_matrix(y_test, y_pred2))
print(classification_report(y_test, y_pred2))

[[23  6]
 [ 3 39]]
              precision    recall  f1-score   support

           b       0.88      0.79      0.84        29
           g       0.87      0.93      0.90        42

    accuracy                           0.87        71
   macro avg       0.88      0.86      0.87        71
weighted avg       0.87      0.87      0.87        71



In [33]:
test_acc_2 = accuracy_score(y_test,y_pred2)

y_pred2_train = svclassifier1.predict(X_train)

train_acc_2 = accuracy_score(y_train,y_pred2_train)

test_acc_2, train_acc_2

(0.8732394366197183, 0.9535714285714286)

### Radial Basis Function Kernel

In [34]:
svclassifier3 = SVC(C=10,kernel='rbf')
svclassifier3.fit(X_train, y_train)

y_pred3 = svclassifier3.predict(X_test)

print(confusion_matrix(y_test, y_pred3))
print(classification_report(y_test, y_pred3))

[[27  2]
 [ 2 40]]
              precision    recall  f1-score   support

           b       0.93      0.93      0.93        29
           g       0.95      0.95      0.95        42

    accuracy                           0.94        71
   macro avg       0.94      0.94      0.94        71
weighted avg       0.94      0.94      0.94        71



In [35]:
test_acc_3 = accuracy_score(y_test,y_pred3)

y_pred3_train = svclassifier1.predict(X_train)

train_acc_3 = accuracy_score(y_train,y_pred3_train)

test_acc_3, train_acc_3

(0.9436619718309859, 0.9535714285714286)

### Printing Comparison Table

In [36]:
data = [['Linear',train_acc_1,test_acc_1],
       ['Quadratic',train_acc_2,test_acc_2],
       ['Radial Basis Function',train_acc_3,test_acc_3]]

In [37]:
data

[['Linear', 0.9535714285714286, 0.7746478873239436],
 ['Quadratic', 0.9535714285714286, 0.8732394366197183],
 ['Radial Basis Function', 0.9535714285714286, 0.9436619718309859]]

In [38]:
df = pd.DataFrame(data,columns=['Kernel','Train Accuracy','Test Accuracy'])

In [39]:
df

Kernel  Train Accuracy  Test Accuracy
0                 Linear        0.953571       0.774648
1              Quadratic        0.953571       0.873239
2  Radial Basis Function        0.953571       0.943662